# Generated by Django 5.1.4 on 2025-01-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location_address', models.CharField(max_length=255)),
                ('lat_lon', models.CharField(max_length=255)),
                ('raised_on', models.DateTimeField()),
                ('ngoid', models.CharField(max_length=255)),
                ('volunteer_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='complaints/')),
            ],
        ),
    ]
