# Generated by Django 5.1.4 on 2025-02-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
