# Generated by Django 5.1.4 on 2025-02-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='image',
        ),
        migrations.AddField(
            model_name='complaint',
            name='imagePath',
            field=models.CharField(default='fgfgf', max_length=3000),
            preserve_default=False,
        ),
    ]
