# Generated by Django 5.1.4 on 2025-02-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_complaint_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('raiseOF', models.CharField(max_length=500)),
            ],
        ),
    ]
