# Generated by Django 5.1.4 on 2025-02-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='raiseOF',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
