# Generated by Django 5.1.4 on 2025-02-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_message_city_alter_message_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='userCheck',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='volunteerCheck',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='volunterWrite',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
