# Generated by Django 5.1.4 on 2025-02-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_complaint_usercheck_complaint_volunteercheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTypes',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=255)),
                ('locations', models.CharField(max_length=255)),
                ('typeOF', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SafeZones',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=255)),
                ('locations', models.CharField(max_length=255)),
                ('typeOF', models.CharField(max_length=255)),
            ],
        ),
    ]
