# Generated by Django 5.1.4 on 2025-02-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_messagetypes_safezones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safezones',
            old_name='locations',
            new_name='LatLon',
        ),
        migrations.RenameField(
            model_name='safezones',
            old_name='message',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='safezones',
            name='typeOF',
        ),
        migrations.RemoveField(
            model_name='safezones',
            name='userid',
        ),
    ]
