# Generated by Django 5.1.4 on 2025-02-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_rename_locations_safezones_latlon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
